// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function __() {
  throw [
        Caml_builtin_exceptions.sys_error,
        "error"
      ];
}

exports.__ = __;
/* No side effect */
