// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Mocha   = require("mocha");
var Assert  = require("assert");
var Helpers = require("../helpers.js");

function koans() {
  Mocha.describe("Expects", function () {
        Mocha.it("Mocha.ok expects a true value", function () {
              Assert.ok(Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("Mocha.eq expects two equal values", function () {
              Assert.equal(1, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("Mocha.neq expects two unequal values", function () {
              Assert.equal(1, Helpers.__(/* () */0));
              return /* () */0;
            });
        return /* () */0;
      });
  return /* () */0;
}

exports.koans = koans;
/* mocha Not a pure module */
