// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Mocha   = require("mocha");
var Assert  = require("assert");
var Helpers = require("../helpers.js");

function makePoint(x, y) {
  return /* record */[
          /* x */x,
          /* y */y
        ];
}

var point = /* record */[
  /* x */1,
  /* y */2
];

function koans() {
  Mocha.describe("Records", function () {
        Mocha.it("a record is a set of named fields", function () {
              Assert.equal(/* record */[
                    /* x */1,
                    /* y */2
                  ], /* record */[
                    /* x */Helpers.__(/* () */0),
                    /* y */Helpers.__(/* () */0)
                  ]);
              return /* () */0;
            });
        Mocha.it("you can access a field with dot notation", function () {
              Assert.equal(1, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("you can extract data with destructuring too", function () {
              Assert.equal(1, Helpers.__(/* () */0));
              return /* () */0;
            });
        return /* () */0;
      });
  return /* () */0;
}

exports.makePoint = makePoint;
exports.point     = point;
exports.koans     = koans;
/* mocha Not a pure module */
