// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Mocha   = require("mocha");
var Assert  = require("assert");
var Helpers = require("../helpers.js");

function koans() {
  Mocha.describe("Literals", function () {
        Mocha.it("strings are enclosed in double quotes", function () {
              Assert.equal("string", Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("characters are enclosed in single quotes", function () {
              Assert.equal(/* "a" */97, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("floats have a decimal", function () {
              Assert.equal(1.0, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("integers do not", function () {
              Assert.equal(1, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("floats can be negative", function () {
              Assert.equal(-1.0, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("integers can be negative", function () {
              Assert.equal(-1, Helpers.__(/* () */0));
              return /* () */0;
            });
        return /* () */0;
      });
  return /* () */0;
}

exports.koans = koans;
/* mocha Not a pure module */
