// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Mocha   = require("mocha");
var Assert  = require("assert");
var Helpers = require("../helpers.js");

function koans() {
  Mocha.describe("Tuples", function () {
        Mocha.it("tuples are like lists of fixed length", function () {
              Assert.equal(/* tuple */[
                    1,
                    2
                  ], Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("tuples may also be of mixed types", function () {
              Assert.equal(/* tuple */[
                    1,
                    "hey"
                  ], Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("first gets the first element of a 2-tuple", function () {
              Assert.equal(1, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("second gets the second element of a 2-tuple", function () {
              Assert.equal("foo", Helpers.__(/* () */0));
              return /* () */0;
            });
        return /* () */0;
      });
  return /* () */0;
}

exports.koans = koans;
/* mocha Not a pure module */
