// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Mocha   = require("mocha");
var Assert  = require("assert");
var Helpers = require("../helpers.js");

function koans() {
  Mocha.describe("Logical Operators", function () {
        Mocha.it("not negates a boolean", function () {
              Assert.equal(/* false */0, 1 - Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("&& is a logical AND", function () {
              Assert.ok(/* true */1 && Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("|| is a logical OR", function () {
              Assert.ok(/* false */0 || Helpers.__(/* () */0));
              return /* () */0;
            });
        return /* () */0;
      });
  return /* () */0;
}

exports.koans = koans;
/* mocha Not a pure module */
