// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Block   = require("bs-platform/lib/js/block.js");
var Mocha   = require("mocha");
var Assert  = require("assert");
var Helpers = require("../helpers.js");

function koans() {
  Mocha.describe("UnionTypes", function () {
        Mocha.it("simple types are similar to enums in other languages", function () {
              Assert.equal(/* C */1, Helpers.__(/* () */0));
              return /* () */0;
            });
        Mocha.it("more complex types can be built with a 'tag' and additional data", function () {
              Assert.equal(/* Base */Block.__(0, [/* C */1]), /* Base */Block.__(0, [Helpers.__(/* () */0)]));
              return /* () */0;
            });
        Mocha.it("switch statements may be used to extract the data from the type", function () {
              Assert.equal(/* A */0, Helpers.__(/* () */0));
              return /* () */0;
            });
        return /* () */0;
      });
  return /* () */0;
}

exports.koans = koans;
/* mocha Not a pure module */
